# Generated by Django 5.2 on 2025-04-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resurses', '0002_alter_counters_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='outgo_elec_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counters',
            name='outgo_elec_night',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counters',
            name='outgo_gas',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counters',
            name='outgo_water',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
    ]
