# Generated by Django 5.2 on 2025-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resurses', '0003_counters_outgo_elec_day_counters_outgo_elec_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='outgo_elec_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
