# Generated by Django 5.2 on 2025-04-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resurses', '0004_alter_counters_outgo_elec_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='outgo_elec_night',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counters',
            name='outgo_gas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counters',
            name='outgo_water',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
