# Generated by Django 5.2 on 2025-04-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resurses', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
