# Generated by Django 5.2 on 2025-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resurses', '0007_document_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
            ],
        ),
    ]
